# Generated by Django 5.2.12 on 2026-03-10 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meslek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('kategori', models.CharField(max_length=50)),
                ('aciklama', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UzmanCevap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uzman_adi', models.CharField(max_length=100)),
                ('soru', models.TextField()),
                ('cevap', models.TextField()),
                ('memnuniyet_skoru', models.IntegerField(default=10)),
                ('ortalama_maas', models.DecimalField(decimal_places=2, max_digits=10)),
                ('meslek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cevaplar', to='pages.meslek')),
            ],
        ),
    ]
