# Generated by Django 5.2.12 on 2026-04-11 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sehir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=100)),
                ('slug', models.SlugField(help_text="URL'de görünecek isim (Örn: istanbul)", unique=True)),
                ('resim', models.ImageField(blank=True, null=True, upload_to='sehirler/')),
                ('tanitim', models.TextField(help_text='Şehir hakkında kısa bir ön bilgi')),
                ('ogrenci_yasam_puani', models.IntegerField(default=5, help_text='1-10 arası bir puan verin')),
                ('ortalama_kira', models.CharField(help_text='Örn: 15.000 TL - 20.000 TL', max_length=50)),
                ('universite_sayisi', models.IntegerField(default=1)),
            ],
        ),
    ]
